---
require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'sorbet/**/*' # VSCode plugin workaround
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/ClassStructure:
  Enabled: true
# doesn't recognize sorbet magic comments
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Exclude:
    - lib/yard-sorbet.rb
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Sorbet/EnforceSignatures:
  Enabled: false
Sorbet/StrictSigil:
  Enabled: false
Sorbet/StrongSigil:
  Enabled: false
Sorbet/TrueSigil:
  Exclude:
    - lib/yard-sorbet/struct_handler.rb
    - spec/**/*
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/Next:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
